default: &default
  adapter: postgresql
  encoding: unicode
  

development:
  <<: *default
  database: my-dairy_dev

test:
  <<: *default
  database: my-dairy_test

production:
  <<: *default
  database: my-dairy
