# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3417dc302fd0138644484b753f86deab79f018a23d2e9f496a67d6278812afe6db6de6030759d6b77142e1df3512fae58c0b0ece4cc989d28fc9f333559b6393

test:
  secret_key_base: 0eccb49c4b0c996026f860d9f4d7f0d601973f0d68b956dc18553e4b14e7ae0f25ba2937c7bb9f1262dbf5227fff83bb06684b3bdef203afcf138be83bdc4a5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
